### ISSUE TITLE
Changed files check

### ISSUE THREAD

**Issue by TarasHoisak** [actions-hub/stylelint#12]
Do you have a possibility to check only changed CSS files, not all CSS files from the project?

**Comment by exelban** [comment]
Yes, please read the documentation to the stylelint.

**Comment by exelban** [comment]
@TarasHoisak not action docs. But [stylelint](https://stylelint.io/user-guide/configure/).

**Comment by TarasHoisak** [comment]
@exelban I didn't find a key for `.stylelintrc` file which will solve a problem to handle only changed files for GitHub action.
Could you please, highlight that key or prop?

**Comment by TarasHoisak** [comment]
BTW: you have an issue with **indentation** in `entrypoint.sh`
