### ISSUE TITLE
Does not find config files with .json extension

### ISSUE THREAD

**Issue by arirawr** [actions-hub/stylelint#3]
My project has a `.stylelintrc.json` config file, and the action does not find the config because of the .json extension. The [check in line 12](https://github.com/actions-hub/stylelint/blob/master/entrypoint.sh#L12) should be changed to accommodate the config formats descibed on the [stylelint website](https://stylelint.io/user-guide/configuration).

**Comment by exelban** [comment]
@arirawr thanks. 

I modify the action. And now action looking for `.stylelintrc*` file.
[v1.1.2](https://github.com/actions-hub/stylelint/releases/tag/v1.1.2)

**Comment by arirawr** [comment]
Thanks @exelban - I updated it on my repo and it works great!
