### ISSUE TITLE
Does it possible to use it with the working directory somehow?

### ISSUE THREAD

**Issue by studentIvan** [actions-hub/stylelint#5]

**Comment by exelban** [comment]
@studentIvan what do you mean `working directory`?

**Comment by studentIvan** [comment]
@exelban it seems it's impossible to use `working-directory` parameter with `uses` https://github.community/t5/GitHub-Actions/use-working-directory-for-entire-job/m-p/45615/highlight/true#M6282 

e.g. I have `web` dir in the github project and need stylelint to be testing only this directory. Not the others (like server, mobile-app, etc)

From the docs:

> You can provide default shell and working-directory options for all run steps in a workflow. You can also set default settings for run that are only available to a job. For more information, see jobs.<job_id>.defaults.run. You cannot use contexts or expressions in this keyword.
> 
> When more than one default setting is defined with the same name, GitHub uses the most specific default setting. For example, a default setting defined in a job will override a default setting that has the same name defined in a workflow.
> 
> Example
> ```yaml
> defaults:
>   run:
>     shell: bash
>     working-directory: scripts
> ```

**Comment by exelban** [comment]
@studentIvan its not possible to use 3d party actions with `run`. And working-directory available only with `run`. 

But it still strange usage. If you want to test some specific folder, you can specify it with `PATTERN` variable. Or in `.stylelintrc`
