### ISSUE TITLE
Error: No files matching the pattern "*.css" were found.

### ISSUE THREAD

**Issue by andyderek** [actions-hub/stylelint#6]
I keep getting this error:

Error: No files matching the pattern "*.css" were found.

Not sure if it is related to Babel or what.

name: Stylesheet Lint
on: [push, pull_request]

jobs:
    linters:
        name: stylelint
        runs-on: ubuntu-latest
      
        steps:
            - uses: actions/checkout@v2
            - uses: actions-hub/stylelint@master

**Comment by exelban** [comment]
Hi. Do you have `.css` files in the root folder (`/`)?

**Comment by andyderek** [comment]
The .css file is in the src folder in the root directory.

**Comment by exelban** [comment]
You need to provide a properly `PATTERN`.

**Comment by andyderek** [comment]
Gotcha.  I’ll try that.  I thought that there was default pattern for .css.

**Comment by exelban** [comment]
Default pattern in `*.css`. So it's looking in the root `/`.

**Comment by andyderek** [comment]
Thank you so much for your time.  It appears to be working correctly now.
