### ISSUE TITLE
Release a new version with fixes

### ISSUE THREAD

**Issue by lpil** [actions-hub/stylelint#8]
Hello! Thank you for this action, we are finding it very useful.

Would it be possible to release a new version of this with the fixes currently on the master branch? We would like to avoid targeting a branch for security reasons.

Thank you,
Louis

**Comment by exelban** [comment]
Hi. Thanks.

Yeap. The new release is ready: [v1.1.3](https://github.com/actions-hub/stylelint/releases/tag/v1.1.3).

**Comment by lpil** [comment]
Thank you
